### PR TITLE
Made register works with exports

### PR DESCRIPTION
**Pull request by Heavenston**
I wanted to use typecheck.macro in my new express project, but all my types are exported for other files to use.
Then I realized typecheck.macro won't register exports, so I forked it and made it work!

### CODE REVIEW

**Comment by vedantroy** [comment]
Wow, I'm super glad you made a fix! Can you add a test? Probably to the `ir/before-passes folder`. Let me know if you have any issues creating a test.

**Comment by Heavenston** [comment]
No problem!

And for the test, I can't export inside a function, so I can't use export inside the test function :/
I'm not sure there's a way to test it? I don't have much experience with ava anyway.

**Comment by vedantroy** [comment]
@Heavenston Hey, just wanted to let you know I will take a look at this soon, I've just been busy implementing some new features :)

**Comment by vedantroy** [comment]
@Heavenston

Can you give a sample piece of Typescript code where this PR works, where the existing library does not? Just want to make sure we're on the same page.

**Comment by Heavenston** [comment]
Won't work currently :
```ts
import createValidation, { register } from 'typecheck.macro'

export interface Foo {
  name: string;
}
register("Foo");
const isFoo = createValidation<Foo>();
```
Will work :
```ts
import createValidation, { register } from 'typecheck.macro'

interface Foo {
  name: string;
}
register("Foo");
const isFoo = createValidation<Foo>();
```

**Comment by vedantroy** [comment]
Thanks! I will add a test for this on  the master branch.

**Pull request merged**
